apiVersion: apps/v1
kind: Deployment
metadata:
  name: large-frontend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: large-frontend-app
  template:
    metadata:
      labels:
        app: large-frontend-app
    spec:
      containers:
      - name: large-frontend-app
        image: deveshrathore13/large-frontend:latest
        ports:
        - containerPort: 80
